export const queryKeys = {
  userDetails: 'userDetails',
  orders: 'orders',
  brands: 'brands',
  categories: 'categories',
  subCategories: 'sub-categories',
  orderDetails: 'order-details',
  productDetails: 'product-details',
  products: 'products',
  blogs: 'blogs',
  blogDetails: 'blog-details',
  googleReviews: 'googleReviews',
  instagramPosts: 'instagramPosts',
  faqs: 'faqs',
  wishlist: 'wishlist',
  homePagePopupDetails: 'homePagePopupDetails',
}
